### PR TITLE
Add a style.css file linked to base.html

### PR DESCRIPTION
**Pull request by Kalwing**
I added a style.css file to base.html, and also linked font from google font in it.
Edited play.html to change the h3 tag on the link, as it made more sense to have a p

The style.css seem to be misinterpreted by the browser.. Don't know why.

### CODE REVIEW

**Comment by schedutron** [comment]
Wow! I appreciate your awesome effort! Let me review this a bit and I will pull soon! Thanks a lot!

**Comment by schedutron** [comment]
@Kalwing Your design looks awesome! Way better than the previous one. Just one more thing - edit `play.html` to update the `src` from `static/` to `static/video`, otherwise, the app won't work. I'll accept your PR after that!

**Comment by Kalwing** [comment]
Oh yeah I totally forgot about that !
hope everything is ok now :)

**Comment by schedutron** [comment]
Everything looks awesome! I'm glad to merge your contributions!

P.S: Would you like to contribute more?

**Comment by Kalwing** [comment]
Thanks a lot !
Sure ! Not sure I can help much tough, I don't know python !

**Comment by schedutron** [comment]
@Kalwing No problem, I'll focus more on the functionality part (Python), while you can add more beauty to this web app. I'll create an issue and let you know about it soon!

**Pull request merged**
