### PR TITLE
Update README and .gitignore

### PR DESCRIPTION
**Pull request by helderberto**
Update README;
Add CONTRIBUTING;
Update .gitignore.

### CODE REVIEW

**Comment by helderberto** [comment]
@syfenx hello, do you see this PR? If this isn't util, I will be close.

**Comment by syfenx** [comment]
I get email updates on this and didn't see the changes at first, looks good to me, thanks.

**Comment by helderberto** [comment]
Nice @syfenx! @schedutron could you make a merge?

**Comment by schedutron** [comment]
@helderburato Thanks a lot! Specifically, the README looks so beautiful now!

**Comment by helderberto** [comment]
@schedutron You're welcome! 💯

**Pull request merged**
