### PR TITLE
Update the README with images.

### LINKED ISSUE #2: Add screenshots to README

### PR DESCRIPTION
**Pull request by pjhampton**
Adds two screenshots to the repo's README.md

Closes #2

### CODE REVIEW

**Comment by xMagerx** [comment]
new img

**Comment by schedutron** [comment]
You've added a couple of pairs. Just one would be enough.

**Comment by schedutron** [comment]
@xMagerx Where?

**Comment by pjhampton** [comment]
@schedutron he / she has just taken my images and added them all to the README. Seems like a PR shark to me.

**Pull request merged**
