### PR TITLE
Feature fav

### PR DESCRIPTION
**Pull request by km4**
Add favicon;
icon from https://www.iconfinder.com/icons/2530844/button_clip_movie_play_video_youtube_icon#size=128

### CODE REVIEW

**Comment by schedutron** [comment]
Looks good to me. Can you give a screenshot of your browser with the app running, and favicon clearly visible?

**Comment by km4** [comment]
https://github.com/schedutron/home-server/issues/14 
I add this favicon screenshot on this PR.

**Comment by schedutron** [comment]
Awesome! Pull-worthy!

**Comment by schedutron** [comment]
Don't forget to star the repo if you liked it :)

**Pull request merged**
